### ISSUE TITLE
Cannot compile latest plugin or use the existing dylib binary

### ISSUE THREAD

**Issue by metaphorz** [Strum/Strums_Mental_VCV_Modules#10]
I get this when trying to compile the source on a Mac:

Strums_Mental_VCV_Modules paul$ make
c++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++ -c -o build/src/MentalClockDivider.cpp.o src/MentalClockDivider.cpp
src/MentalClockDivider.cpp:180:43: error: use of undeclared identifier
      'gSampleRate'
                        lights[0] -= lights[0] / lightLambda / gSampleRate;

(along with 4 or 5 more gSampleRate related errors)...

Also, the binary library posted on the plugin list is not working with 0.4.0

Ideas on either of the above issues?
